services:
  - type: web
    name: sva-yolo-flask
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python app.py
    envVars:
      - key: PORT
        value: "5000"