services:
  - type: static_site
    name: sva-notebooks
    buildCommand: pip install nbconvert && jupyter nbconvert --to html *.ipynb && mkdir -p docs && mv *.html docs/
    staticPublishPath: ./docs